version: "3"

services:
  mongo:
    restart: always
    container_name: mongo_cont
    image: mongo
    ports:
      - "27017:27017"

  ejercicios:
    restart: "no"
    build: .
    container_name: node_js_course
    image: node_js:course
    depends_on:
      - mongo
    environment:
      - UDEV=1
    ports:
      - "3000:3000" # Map 8000 to 8000 of our docker image
    privileged: true
    volumes:
      - ./ejercicios:/ejercicios # Map ./app directory en docker app folder
    cap_add:
      - SYS_ADMIN
    devices:
      - '/dev:/dev'
    command: sh -c "cd ./utn-ecommerce && DEBUG=utn-ecommerce:* npm start"
     # sh -c "DEBUG=utn-ecommerce:* npm start"


