version: "3"

services:

  ejercicios:
    restart: always
    build: .
    container_name: node_js_course
    image: node_js:course
    environment:
      - UDEV=1
    ports:
      - "8000:8000" # Map 8000 to 8000 of our docker image
    privileged: true
    volumes:
      - ./ejercicios:/ejercicios # Map ./app directory en docker app folder
    cap_add:
      - SYS_ADMIN
    devices:
      - '/dev:/dev'
    command: >
      sh -c "node ejercicio2.js"


